- index.spec.js
- knexfile.js
added testing config and an index.spec.js file.
> added testing config to knex and example index.spec.js

- knexfile.js
fixed migration and seed directories.
pointed development and testing environments to localhost.
> pointed test and dev environments to localhost

- data/migrations/20191022214415_createTables.js
Creating initial db migrations.
Added tables for users, client profiles, talent profiles, jobs, and job offers.
> Migrations

- data/dbConfig.js
- index.js
- users/userRouter.js
Fixed some typos.
Added an OR statement in the dbConfig file environment variable.
> typos + fix dbConfig

- auth/authRouter.js
- data/migrations/20191022214415_createTables.js
- knexfile.js
setup the development and testing environments to use variables from the .env file so the database name and credentials are not posted to github.
> Local dbfix

- jobs/jobModel.js
- jobs/jobRouter.js
- server.js
Added a /api/jobs endpoint with post, put, and delete functions.
> Added /api/jobs endpoint

- jobOffers/jobOfferModel.js
- jobOffers/jobOfferRouter.js
- server.js
Added /api/jobs/:jobId/offers endpoint with CRUD functions.
> added /api/jobs/:jobId/offers endpoint

- knexfile.js
Fixes Postgres connection issue
> Pg connection

- clientProfiles/clientProfileModel.js
- clientProfiles/clientProfileRouter.js
- server.js
Implemented endpoint for client profiles at /api/clients
> Client profile endpoint

- data/migrations/20191022214415_createTables.js
- knexfile.js
made username and password notnullable
> Require unpw

- clientProfiles/clientProfileModel.js
Add user info when querying client profiles
> Add users to client profile

- talentProfiles/talentProfileModel.js
- talentProfiles/talentProfileRouter.js
> added talent profile endpoint at /api/actors

- data/migrations/20191022214415_createTables.js
- data/seeds/development/000 - cleaner.js
- data/seeds/development/001 - Users.js
- data/seeds/development/002 - ClientProfiles.js
- data/seeds/development/003 - TalentProfiles.js
- data/seeds/development/004 - Jobs.js
- package.json
- yarn.lock
added seeds for easier testing/QA
> Ready to Merge: Seeds

- clientProfiles/clientProfileModel.js
- talentProfiles/talentProfileModel.js
- users/userModel.js
- users/userRouter.js
> added users endpoint

- auth/authRouter.js
- users/userModel.js
added userType to token payload
> added userType to token payload

- auth/authRouter.js
- server.js
passing userId and userType  back during login
> BE login userID + userType

- users/userRouter.js
> Added user security to the userRouter with a secret.

- data/migrations/20191022214415_createTables.js
- data/seeds/development/004 - Jobs.js
- jobOffers/jobOfferRouter.js
Removed notNullable constraint on previousOffer in jobOffers.
> Ready To Merge: Previous offer nullable

- auth/authenticate-middleware.js
- server.js
Added token authentication middleware to protect endpoints. Tested with postman and it is working as expected. Dependent on Front end sending axios requests with an authentication token.
> Protect endpoints

- clientProfiles/clientProfileModel.js
- clientProfiles/clientProfileRouter.js
added getJobsByClientId to ClientProfile Model and Router.
> added getJobsByClientId

- users/userRouter.js
updated validateUser middleware to check userId from decoding the token to the id specified in the endpoint URL.
> changed validateUser to check IDs instead of the secret

- clientProfiles/clientProfileModel.js
Changes put request in clientProfileRouter.js to use userId as identifying parameter rather than clientId.
> Client profile put request

- data/migrations/20191022214415_createTables.js
- data/seeds/development/001 - Users.js
- data/seeds/development/002 - ClientProfiles.js
- data/seeds/development/003 - TalentProfiles.js
- data/seeds/development/004 - Jobs.js
- jobs/jobModel.js
Adding more data to display on the front-end
> Migration changes

- data/migrations/20191022214415_createTables.js
- jobOffers/jobOfferRouter.js
- jobs/jobRouter.js
> added status to job table:

- talentProfiles/talentProfileModel.js
/api/talents endpoint now pulls in user information (name, email, etc.) for the talents.
> Get talent profiles

- data/seeds/development/004 - Jobs.js
status was missing from Job seeds
> Add seed status

- data/seeds/development/005-languages.js
- data/seeds/development/006-accents.js
Adding seeds for languages/accents
> added language/accent seeds

- data/migrations/20191022214415_createTables.js
- jobs/jobModel.js
- talentProfiles/talentProfileModel.js
- talentProfiles/talentProfileRouter.js
Various fixes to job model and getTalentByTalentId
> Job model change

- .gitignore
- knexfile.js
- package.json
- server.js
- uploads/signS3.js
- yarn.lock
Added ability to create signed s3 urls to upload files from the front-end
> Voice sample be

- .env
- .gitignore
- clientProfiles/clientProfileModel.js
- clientProfiles/clientProfileRouter.js
- cronJob.js
- data/seeds/development/001 - Users.js
- data/seeds/development/007-JobOffers.js
- index.js
- jobOffers/jobOfferModel.js
- jobs/jobModel.js
- jobs/jobRouter.js
- package.json
- talentProfiles/talentProfileModel.js
- yarn.lock
> Loyalty System

- data/migrations/20191022214415_createTables.js
- server.js
- talentVoiceSamples/voiceSampleModel.js
- talentVoiceSamples/voiceSampleRouter.js
> Added talentVoiceSamples into the migrations tables.

- talentVoiceSamples/voiceSampleRouter.js
Export router from voiceSampleRouter.js
Error on starting server because router was not exported
> Export router in voiceSampleRouter.js

- auth/authRouter.js
- data/seeds/development/001 - Users.js
- data/seeds/development/003 - TalentProfiles.js
- data/seeds/development/004 - Jobs.js
- jobs/jobRouter.js
- talentProfiles/talentProfileModel.js
- talentProfiles/talentProfileRouter.js
…endpoint (need to figure out float parsing in the future).
> Updated Complete Job

- server.js
- talentVoiceSamples/voiceSampleModel.js
> Modify endpoint that adds S3 URL to database

- talentProfiles/talentProfileModel.js
> When getting talent, it now returns the loyaltyLevel and gender

- talentProfiles/talentProfileModel.js
- talentProfiles/talentProfileRouter.js
Endpoint for fetching voice samples from a user
> Voice sample

- reviews/reviewModel.js
- reviews/reviewRouter.js
Added jobId to routes and duplicate check for reviews
> Added jobId to routes and duplicate check for reviews

- reviews/reviewRouter.js
Fixed a typo in the review router.
Changed getReviewsByUserId to getReviewsByAuthorId
> fixed a typo in the review router

- api/server.js
- middleware/authenticate.js
- models/attrVoiceSampleModel.js
- models/attributesModel.js
- models/voiceSamplesModel.js
- routers/attributeRouter.js
- routers/avsRouter.js
- routers/voiceSampleRouter.js
server.js
added endpoints for attributes and attrVoiceSamples to server
authenticate.js
fixed case issue in req.headers.authorization for proper token reading
attrVoiceSampleModel.js
updated findAll method to properly retrieve all attributes associated with voice sample
attributesModel.js
updated find method to properly filter queries
updated findById method to not return a single element array
added udpate functionality for attributes
voiceSamplesModel.js
updated find method to properly retrieve all associated attributes
added removeSample method
attributeRouter.js
created endpoints for CRUD functionality
avsRouter.js
created endpoints for CRUD functionality
voiceSampleRouter.js
created endpoints for CRUD functionality
> Voice samples

- README.md
Accidentally used the incorrect badges on readme file, correct badges are there now
> fixed to correct badges

- models/voiceSamplesModel.js
updated the delete function to also delete all attribute relations
> added relation deletion to the voice sample delete function

- models/userModel.js
- models/voiceSamplesModel.js
- package.json
- routers/userRouter.js
- routers/voiceSampleRouter.js
added filtering endpoint for voice samples.
> Query builder

- models/voiceSamplesModel.js
Find method now returns all voice sample columns
> updated find method to properly return all voice sample columns

- routers/userRouter.js
As the title says, set to return array
> changed query by display name to return an array

- .github/workflows/ci.yml
added .yml file for Code Climate test coverage
> added yml file for test coverage

- .github/workflows/ci.yml
- models/attributesModel.js
- models/userModel.js
- models/voiceSamplesModel.js
reworked how attributes are added to samples
> Attributes

- routers/attributeRouter.js
> fixed typo

- models/attributesModel.js
was handling parameters wrong.
> fixed error in handling of parameters

- models/attrVoiceSampleModel.js
as the title says, I broke it, and now I fixed it
> forgot to add .first(), so it broke

- models/attrVoiceSampleModel.js
forgot another thing, it is fixed
> forgot to add .id to relationID

- package.json
added coverage script to package.json for codeclimate
> added coverage script to package.json

- .github/workflows/ci.yml
Changed coverage file locations to match what needs to be tested
> working on the yml file to get test coverage working properly

- .github/workflows/ci.yml
Changed version on codeclimate from 2.6.0 to 2.4.0
> Code coverage

- .github/workflows/ci.yml
fixed the omission of a few lines of code in the yml file.
> fixed error in yml file

- models/userModel.js
> added logging to work out a bug

- models/userModel.js
added another log to work out a bug
> added another log

- models/userModel.js
added code to remove null values from userIds array
> added protection for removing null users

- package.json
updated coverage collection patterns
> updated coverage patterns

- models/userModel.js
- routers/userRouter.js
removed functions for adding an avatar to user, ran out of time to get it working.
> removed add avatar to user, ran out of time to add it

- .github/workflows/ci.yml
> updated secrets in yml file for actions to work

- package.json
working on package file to get codeclimate test coverage working
> working on testing for codeclimate

- package.json
undoing changes that broke testing
> undoing changes

- package.json
changed testing to test to match knexfile
> changed DB_ENV to test to match the knexfile

- .github/workflows/ci.yml
changed node_env from testing to ${{ secrets.NODE_ENV }}
> updated node_env

- models/attributesModel.js
added function to check if duplicate tag
> hopefully fixing duplication issue

- models/attributesModel.js
- routers/attributeRouter.js
Added a function to check if the attribute being added is already tied to a sample. if it is then it returns null.
> Attribute bugs
